export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // return <div className="h-screen overflow-hidden">{children}</div>;
  return (
    <div className="h-screen w-full flex items-center justify-center">
      {children}
    </div>
  );
}
